version: '3'

services:
  backend:
    image: cpusch/sweng-final-project-backend:latest
    networks:
      - my-net
    ports:
      - 80
  frotend:
    image: cpusch/sweng-final-project-frontend:latest
    networks:
      - my-net
    ports:
      - 4680:3000
    command: npm start
networks:
  my-net:
    driver: bridge
