name: Publish Docker images
on:
  release:
    types: [created]
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build backend docker image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/sweng-final-project-backend:latest
      - name: Build frontend docker image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./Frontend/engineer-productivity/
          file: ./Frontend/engineer-productivity/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/sweng-final-project-frontend:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
