name: Publish Docker images
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build backend docker image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sweng_final_project:latest
      - name: Build frontend docker image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile2
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sweng_final_project:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
